use std::collections::HashMap;
use std::fs;
use std::io::{self, IsTerminal, Read, Write};
use std::path::Path;

use anyhow::{Context, Result};
use regex::Regex;
use std::sync::LazyLock;

static TOKEN_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"\[([A-Z]+_\d{3,})\]").unwrap()
});

/// Read input from file or stdin (D-06).
/// If no file given and stdin is a terminal, print usage hint and bail.
pub fn read_input(file: Option<&Path>) -> Result<String> {
    match file {
        Some(path) => {
            fs::read_to_string(path)
                .with_context(|| format!("Cannot read file: {}", path.display()))
        }
        None => {
            if io::stdin().is_terminal() {
                anyhow::bail!(
                    "No input provided. Pipe text or specify a file:\n  \
                     logtok detokenize response.txt\n  \
                     echo '...' | logtok detokenize"
                );
            }
            let mut buf = String::new();
            io::stdin().read_to_string(&mut buf)?;
            Ok(buf)
        }
    }
}

/// Replace all [CATEGORY_NNN] tokens in text with real values from the token map (D-09).
/// Tokens not found in the map are left as-is (graceful degradation).
pub fn detokenize(text: &str, token_to_value: &HashMap<String, String>) -> DetokenizeResult {
    let re = &*TOKEN_RE;
    let mut replaced_count = 0u32;
    let mut unresolved_count = 0u32;

    let result = re.replace_all(text, |caps: &regex::Captures| {
        let token = &caps[0]; // includes brackets, e.g. [IP_001]
        match token_to_value.get(token) {
            Some(value) => {
                replaced_count += 1;
                value.clone()
            }
            None => {
                unresolved_count += 1;
                token.to_string()
            }
        }
    });

    DetokenizeResult {
        text: result.to_string(),
        replaced_count,
        unresolved_count,
    }
}

pub struct DetokenizeResult {
    pub text: String,
    pub replaced_count: u32,
    pub unresolved_count: u32,
}

/// Write de-tokenized output to stdout (D-08, D-11) or markdown file (D-12).
pub fn write_output(result: &DetokenizeResult, detailed: Option<&Path>) -> Result<()> {
    match detailed {
        Some(path) => {
            // D-12: Write full markdown report to file
            let mut content = String::new();
            content.push_str("# Diagnosis Report\n\n");
            content.push_str("*Generated by logtok detokenize*\n\n");
            content.push_str("---\n\n");
            content.push_str(&result.text);
            content.push_str("\n\n---\n\n");
            content.push_str(&format!(
                "*{} tokens resolved, {} unresolved*\n",
                result.replaced_count, result.unresolved_count
            ));
            fs::write(path, &content)
                .with_context(|| format!("Cannot write report: {}", path.display()))?;
            eprintln!("logtok: report written to {}", path.display());
            Ok(())
        }
        None => {
            // D-08, D-11: Print directly to stdout
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            handle.write_all(result.text.as_bytes())?;
            // Ensure trailing newline
            if !result.text.ends_with('\n') {
                handle.write_all(b"\n")?;
            }
            handle.flush()?;
            Ok(())
        }
    }
}
